- platform: mqtt
  schema: template
  name: "Entrance Light"
  command_topic: "shellies/shellybulb-3CC259/color/0/set"
  state_topic: "shellies/shellybulb-3CC259/color/0/status"
  availability_topic: "shellies/shellybulb-3CC259/online"
  payload_available: 'true'
  payload_not_available: 'false'
  effect_list:
    - "0 Off"
    - "1 Meteor Shower"
    - "2 Gradual Change"
    - "3 Breath"
    - "4 Flash"
    - "5 On/Off Gradual"
    - "6 Red/Green Change"
  command_on_template: >
    {
    {%- if brightness is not defined and red is not defined and effect is not defined -%}  
    "turn":"on"
    {%- endif -%}
    {%- if brightness is defined -%}
    "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {%- if white_value is defined -%}
    "white": {{ white_value }}
    {%- endif -%}
    {%- if effect is defined -%}
    "effect": {{ effect[0] }}
    {%- endif -%}
    }
  command_off_template: '{"turn":"off"}'
  state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  effect_template: '{{ value_json.effect }}'
  qos: 2
  